# Generated by Django 4.1.4 on 2022-12-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='uid',
            field=models.CharField(max_length=200),
        ),
    ]
