# Generated by Django 4.1.4 on 2022-12-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_admin_admin_uid_alter_service_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='name_nonce',
            field=models.CharField(default='value', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secret',
            name='value_nonce',
            field=models.CharField(default='value', max_length=64),
            preserve_default=False,
        ),
    ]
