# Generated by Django 4.1.4 on 2022-12-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_secret_name_nonce_secret_value_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.DeleteModel(
            name='ServiceSalt',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
